In [73]:
import pandas as pd

df = pd.read_csv('crime.csv')
df.head()

,연도,구분,강력범죄,절도범죄,폭력범죄,지능범죄,풍속범죄,특별경제범죄,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,선거범죄,병역범죄,기타범죄
0,2014,발생건수,800,900,750,650,700,1034,600,850,800,900,750,800,700,1000
1,2014,검거건수,500,600,400,450,400,961,350,500,450,550,400,450,400,600
2,2015,발생건수,900,768,800,750,700,1000,850,800,900,950,800,850,750,1000
3,2015,검거건수,600,713,500,550,400,600,500,450,550,600,450,500,400,600
4,2016,발생건수,850,800,880,750,700,950,900,800,850,900,750,800,700,950

In [74]:
df_a = pd.melt(df, id_vars=["연도", "구분"], var_name="범죄유형", value_name="건수")

In [75]:
df_a.head()

     연도    구분  범죄유형   건수
0  2014  발생건수  강력범죄  800
1  2014  검거건수  강력범죄  500
2  2015  발생건수  강력범죄  900
3  2015  검거건수  강력범죄  600
4  2016  발생건수  강력범죄  850

In [76]:
df_b = df_a.pivot_table(index=['연도', '범죄유형'], columns='구분', values='건수').reset_index()

In [77]:
df_b.head()

구분    연도  범죄유형   검거건수    발생건수
0   2014  강력범죄  500.0   800.0
1   2014  교통범죄  550.0   900.0
2   2014  기타범죄  600.0  1000.0
3   2014  노동범죄  400.0   750.0
4   2014  마약범죄  350.0   600.0

In [78]:
df_b['검거율'] = df_b['검거건수'] / df_b['발생건수']

df_b.head()

구분    연도  범죄유형   검거건수    발생건수       검거율
0   2014  강력범죄  500.0   800.0  0.625000
1   2014  교통범죄  550.0   900.0  0.611111
2   2014  기타범죄  600.0  1000.0  0.600000
3   2014  노동범죄  400.0   750.0  0.533333
4   2014  마약범죄  350.0   600.0  0.583333

In [79]:
max_crime = df_b.groupby('연도')['검거율'].idxmax()

In [81]:
df_b.loc[max_crime]['검거건수'].sum()

np.float64(7799.0)