## 문제 3
제공된 데이터(order_data.csv)는 온라인 쇼핑몰의 주문 데이터입니다. 전처리 후 아래 소문제를 각각 구하시오.
[전처리 수행]
• 새로운 컬럼 order_amt 생성: order_amt = quantity X price
• 새로운 컬럼 cancel_TF 생성: 주문번호가 'C'로 시작하면 True, 아니면 False (C'는 취소 주문)
• cancel_TF가 T인 행의 order_amt를 음수로 변환
문제 3-1 취소 주문 중 order_amt의 절댓값이 가장 큰 주문번호를 구하시오.
문제 3-2 고객ID(Cus_id)별로 order_amt를 합산하여 가장 큰 값을 소수점 둘째 자리까지 구하시오.

In [9]:
import pandas as pd

df = pd.read_csv('order_data.csv')
df.head()

  order_no   cus_id  product  quantity   price
0   536342  CUS0084  Monitor         2  110.02
1  C536505  CUS0058  Headset         2   52.11
2   536522  CUS0027  Headset         3   93.67
3   536544  CUS0077  Headset         3   74.05
4   536682  CUS0089  Headset         2  115.39

In [10]:
df.isnull().sum()

order_no    0
cus_id      0
product     0
quantity    0
price       0
dtype: int64

In [12]:
df['order_amt'] = df['quantity'] * df['price']
df['cancel_TF'] = df['order_no'].str[0] == 'C'

cond = df['cancel_TF'] == True
df.loc[cond, 'order_amt'] = -df.loc[cond, 'order_amt']
df.head()

  order_no   cus_id  product  quantity   price  order_amt  cancel_TF
0   536342  CUS0084  Monitor         2  110.02     220.04      False
1  C536505  CUS0058  Headset         2   52.11    -104.22       True
2   536522  CUS0027  Headset         3   93.67     281.01      False
3   536544  CUS0077  Headset         3   74.05     222.15      False
4   536682  CUS0089  Headset         2  115.39     230.78      False

In [23]:
cond2 = df['cancel_TF'] == True
max_index = df.loc[cond2, 'order_amt'].abs().idxmax()
max_index

np.int64(185)

In [25]:
df.loc[max_index, 'order_no']

'C542426'

In [29]:
df.groupby('cus_id')['order_amt'].sum().max()

np.float64(2877.21)