In [5]:
import pandas as pd
from scipy.stats import chi2_contingency

observed = pd.DataFrame([[50, 30], [60, 40]])
print(chi2_contingency(observed))

Chi2ContingencyResult(statistic=np.float64(0.03535714285714309), pvalue=np.float64(0.8508492527705047), dof=1, expected_freq=array([[48.88888889, 31.11111111],
       [61.11111111, 38.88888889]]))

In [6]:
df = pd.DataFrame({
        '캠프': ['빅분기']*80 + ['정처기']*100,
        '등록여부': ['등록']*50 + ['등록안함']*30 + ['등록']*60 + ['등록안함']*40
})

df.head()

    캠프 등록여부
0  빅분기   등록
1  빅분기   등록
2  빅분기   등록
3  빅분기   등록
4  빅분기   등록

In [7]:
df = pd.crosstab(df['캠프'], df['등록여부'])
df

등록여부  등록  등록안함
캠프
빅분기   50    30
정처기   60    40

In [8]:
from scipy.stats import chi2_contingency

print(chi2_contingency(observed))

Chi2ContingencyResult(statistic=np.float64(0.03535714285714309), pvalue=np.float64(0.8508492527705047), dof=1, expected_freq=array([[48.88888889, 31.11111111],
       [61.11111111, 38.88888889]]))

In [10]:
pvalue

np.float64(0.00018567620386641424)

1. 0.03
2. 22.1666
3. 0.000185
4. 기각